#!/bin/sh
./simple-tga-parser ./tga_files/samples/CBW8_.TGA
./simple-tga-parser ./tga_files/samples/CCM8_.TGA
./simple-tga-parser ./tga_files/samples/CTC16.TGA
./simple-tga-parser ./tga_files/samples/CTC24.TGA
./simple-tga-parser ./tga_files/samples/CTC32_.TGA
./simple-tga-parser ./tga_files/samples/FLAG_B16.TGA
./simple-tga-parser ./tga_files/samples/FLAG_B24.TGA
./simple-tga-parser ./tga_files/samples/FLAG_B32_.TGA
./simple-tga-parser ./tga_files/samples/FLAG_T16_.TGA
./simple-tga-parser ./tga_files/samples/FLAG_T32_.TGA
./simple-tga-parser ./tga_files/samples/MARBLES.TGA
./simple-tga-parser ./tga_files/samples/UBW8_.TGA
./simple-tga-parser ./tga_files/samples/UCM8_.TGA
./simple-tga-parser ./tga_files/samples/UTC16.TGA
./simple-tga-parser ./tga_files/samples/UTC24.TGA
./simple-tga-parser ./tga_files/samples/UTC32_.TGA
./simple-tga-parser ./tga_files/samples/XING_B16.TGA
./simple-tga-parser ./tga_files/samples/XING_B24.TGA
./simple-tga-parser ./tga_files/samples/XING_B32_.TGA
./simple-tga-parser ./tga_files/samples/XING_T16.TGA
./simple-tga-parser ./tga_files/samples/XING_T24.TGA
./simple-tga-parser ./tga_files/samples/XING_T32_.TGA
./simple-tga-parser ./tga_files/samples/grayscale_LL.tga
./simple-tga-parser ./tga_files/samples/grayscale_LR.tga
./simple-tga-parser ./tga_files/samples/grayscale_UL.tga
./simple-tga-parser ./tga_files/samples/grayscale_UR.tga
./simple-tga-parser ./tga_files/samples/grayscale_a_LL.tga
./simple-tga-parser ./tga_files/samples/grayscale_a_LR.tga
./simple-tga-parser ./tga_files/samples/grayscale_a_UL.tga
./simple-tga-parser ./tga_files/samples/grayscale_a_UR.tga
./simple-tga-parser ./tga_files/samples/grayscale_a_rle_LL.tga
./simple-tga-parser ./tga_files/samples/grayscale_a_rle_LR.tga
./simple-tga-parser ./tga_files/samples/grayscale_a_rle_UL.tga
./simple-tga-parser ./tga_files/samples/grayscale_a_rle_UR.tga
./simple-tga-parser ./tga_files/samples/grayscale_rle_LL.tga
./simple-tga-parser ./tga_files/samples/grayscale_rle_LR.tga
./simple-tga-parser ./tga_files/samples/grayscale_rle_UL.tga
./simple-tga-parser ./tga_files/samples/grayscale_rle_UR.tga
./simple-tga-parser ./tga_files/samples/indexed_LL.tga
./simple-tga-parser ./tga_files/samples/indexed_LR.tga
./simple-tga-parser ./tga_files/samples/indexed_UL.tga
./simple-tga-parser ./tga_files/samples/indexed_UR.tga
./simple-tga-parser ./tga_files/samples/indexed_a_LL.tga
./simple-tga-parser ./tga_files/samples/indexed_a_LR.tga
./simple-tga-parser ./tga_files/samples/indexed_a_UL.tga
./simple-tga-parser ./tga_files/samples/indexed_a_UR.tga
./simple-tga-parser ./tga_files/samples/indexed_a_rle_LL.tga
./simple-tga-parser ./tga_files/samples/indexed_a_rle_LR.tga
./simple-tga-parser ./tga_files/samples/indexed_a_rle_UL.tga
./simple-tga-parser ./tga_files/samples/indexed_a_rle_UR.tga
./simple-tga-parser ./tga_files/samples/indexed_rle_LL.tga
./simple-tga-parser ./tga_files/samples/indexed_rle_LR.tga
./simple-tga-parser ./tga_files/samples/indexed_rle_UL.tga
./simple-tga-parser ./tga_files/samples/indexed_rle_UR.tga
./simple-tga-parser ./tga_files/samples/rgb_LL.tga
./simple-tga-parser ./tga_files/samples/rgb_LR.tga
./simple-tga-parser ./tga_files/samples/rgb_UL.tga
./simple-tga-parser ./tga_files/samples/rgb_UR.tga
./simple-tga-parser ./tga_files/samples/rgb_a_LL.tga
./simple-tga-parser ./tga_files/samples/rgb_a_LR.tga
./simple-tga-parser ./tga_files/samples/rgb_a_UL.tga
./simple-tga-parser ./tga_files/samples/rgb_a_UR.tga
./simple-tga-parser ./tga_files/samples/rgb_a_rle_LL.tga
./simple-tga-parser ./tga_files/samples/rgb_a_rle_LR.tga
./simple-tga-parser ./tga_files/samples/rgb_a_rle_UL.tga
./simple-tga-parser ./tga_files/samples/rgb_a_rle_UR.tga
./simple-tga-parser ./tga_files/samples/rgb_rle_LL.tga
./simple-tga-parser ./tga_files/samples/rgb_rle_LR.tga
./simple-tga-parser ./tga_files/samples/rgb_rle_UL.tga
./simple-tga-parser ./tga_files/samples/rgb_rle_UR.tga
